### ISSUE TITLE
YAML based raw knowledge

### ISSUE THREAD

**Issue by pepellou** [pepellou/little-chomsky#5]
Let's say we have a knowledge base stored in YAML files, for example:

`teachers.yml`
```
teachers:
   - name: Ángel Eugenio
     lastname: Abuín González
     department: Lengua y Literatura Españolas, Teoría de la Literatura y Lingüística General
     ...
   - name: Juan Carlos
     lastname: Acuña Fariña
     department: Filología Inglesa
     ...
```

QUESTION: What is the department of Ángel Eugenio?
ANSWER: Lengua y Literatura Españolas, Teoría de la Literatura y Lingüística General

The spec for such a rule would be something like this:
```
   - input: What is the department of {name}?
     answer: The department of {name} is {department}
     where:
         department: teachers[name={name}].department
```

Several types of queries should be possible, but mainly:

- Select list: `teachers`
- Filter list by attribute: `teachers[name={name}]`
- Sort list by attribute: `teachers|sort(name,asc)`
- Select element by index: `teachers|sort(name,asc)[0]`
- Select attribute: `teachers[0].name`
- Select attribute of list: `teachers.name`

All results will have a string representation. An array of 1 element is represented same as the element. This explains how this query works:
```
teachers[name={name}].department
```
Note that the result is not the value of an attribute of a single element, but an array with 1 value, since `teachers[name={name}]` is a list despite having 1 element.
